---
- name: replace yarn-site.yml and notify
  template: src=yarn-site.xml dest="{{ hadoop_home }}/etc/hadoop/yarn-site.xml" 
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart hadoop-datanode
   - restart yarn-nodemanager

- name: replace hdfs-site.yml and notify
  template: src=hdfs-site.xml dest="{{ hadoop_home }}/etc/hadoop/hdfs-site.xml"
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart hadoop-datanode
   - restart yarn-nodemanager

- name: replace core-site.yml and notify
  template: src=core-site.xml dest="{{ hadoop_home }}/etc/hadoop/core-site.xml" 
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart hadoop-datanode
   - restart yarn-nodemanager

- name: replace mapred-site.yml and notify
  template: src=mapred-site.xml dest="{{ hadoop_home }}/etc/hadoop/mapred-site.xml" 
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart hadoop-datanode
   - restart yarn-nodemanager

#- template: src=slaves dest="{{ hadoop_home }}/etc/hadoop/slaves" owner=root group=root
#  notify:
#   - refreshDFSNodes
#   - refreshYarnNodes
#   - restart hadoop-datanode
#   - restart yarn-nodemanager

- name: namenode -format creares=/tmp/hadoop-root/dfs/name
  command: "{{ hadoop_home }}/bin/hdfs namenode -format creates=/tmp/hadoop-root/dfs/name"
  when: (hadoop_type_of_node == 'master') or (hadoop_type_of_node == 'namenode')



