---
# RedHat related OSs
- name: Yum install {{ item }}
  yum:
    name={{ item }} state=installed
  when: "ansible_os_family == 'RedHat'"
  with_items:
  - wget
  - tar
  - gzip
  - unzip
  - java-1.8.0-openjdk

# Ubuntu releate OS
- name: Ubuntu 16 install software-properties-common
  apt: name=software-properties-common
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

- name: Ubuntu 16 install OpenJDK PPA repo
  apt_repository: repo='ppa:openjdk-r/ppa'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

# Debian related OSs need install
- name: Apt install {{ item }}
  action: apt pkg={{ item }} state=installed update_cache=yes cache_valid_time=604800
  when: "ansible_os_family == 'Debian'"
  with_items:
  - wget
  - tar                                                  
  - gzip
  - unzip
  - openjdk-8-jre      

- name: Download hadoop version, default hadoop-2.7.4.tar.gz
  get_url: 
    url={{ hadoop_mirrors|random }}/hadoop-{{ hadoop_version }}.tar.gz 
    dest=/opt/hadoop-{{ hadoop_version }}.tar.gz
    force=no
  register: result
  until: result|success
  #retries: 5
  retries: 1
  delay: 2
  tags:
  - down

- unarchive: src=/opt/hadoop-{{ hadoop_version }}.tar.gz dest=/opt creates=/opt/hadoop-{{ hadoop_version }} copy=no
  tags:
  - untar

- file: dest={{ hadoop_home }} src=/opt/hadoop-{{ hadoop_version }} state=link

- file: dest=/opt/hadoop src={{ hadoop_home }} state=link

- lineinfile: dest="{{ hadoop_home }}/etc/hadoop/hadoop-env.sh" regexp=JAVA_HOME= line="export JAVA_HOME={{item}}"
  with_first_found:
   - /usr/lib/jvm/java-8-openjdk-amd64
   - /usr/lib/jvm/jre-1.8.0

