---
# Add a fast check to speed reconfiguration
- stat: path=/opt/hadoop
  register: hadoop_installed
  tags:
  - judge
- include: install.yml
  when: not hadoop_installed.stat.exists
  tags:
  - install
- include: configure.yml
